#################
#				#
# IMAGE SECTION #
#				#
#################

images:
- {name: '<span class="link">Cable Beach, Nassau, Bahamas</span>', title: '<span class="loadTitle">Sandals Resort</span>',  image: 'proj1'}
- {name: '<span class="link">1 Valencia Dr, Miami Beach, FL 33109</span>', title: '<span class="loadTitle">Fisher Resort</span>', image: 'proj2'}
- {name: '<span class="link">Camino a Veracruz Km 7, Panama</span>', title: '<span class="loadTitle">Playa Bonita Resort</span>', image: 'proj3'}

gallery:
- {name: 'Blue Ridge Mountains, Va.', image: '1'}
- {name: 'Kirawira Luxury Tented Camp, Tanzania', image: '2'}
- {name: 'Costa Rica at Peninsula Papagayo', image: '3'}
- {name: 'Palazzo Avino, Ravello', image: '4'}
- {name: 'Rosalie Bay Resort, Roseau', image: '5'}
- {name: 'Capella Ixtapa', image: '6'}
- {name: 'Splendido Mare, Portofino', image: '7'}
- {name: 'Kaupulehu, Big Island', image: '8'}
- {name: 'CordeValle, San Martin, Calif.', image: '9'}
- {name: 'Park Hyatt Dubai', image: '10'}
- {name: 'The Peninsula, Bangkok', image: '11'}
- {name: 'El Dorado Maroma Yucatán', image: '12'}
- {name: 'Sandals Resort', image: '13'}
- {name: 'Fisher Resort', image: '14'}
- {name: 'Playa Bonita Resort', image: '15'}


testimonials:
- {name: 'Hank Rowley', image: '0', quote: "'Beach Retreat was the perfect answer for me when I didn't quite know what I wanted to do.  They gave me numerous options to choose from so I had the perfect vacation!'"}
- {name: 'Carmen Liz', image: '14', quote: "'I am not a big vacation person so I was struggling with ways to find good vacation locations.  Beach Retreat does a great job of giving you a good amount of spots to choose from!'"}
- {name: 'Everette Harlan', image: '2', quote: "'I normally only vacation to the same places all of the time because I didn't know where to search for new vacation spots.  Beach Retreat does a great job by putting all of your choices in one website!'"}

